spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/siteforge_db}
    username: ${DB_USER:siteforge}
    password: ${DB_PASSWORD:siteforge}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

cms:
  preview-base-url: http://localhost:8100/web
